workflows:
  android-build:
    name: Android APK Build
    instance_type: mac_mini_m2  # Use 'linux' for non-M1 builds
    max_build_duration: 30
    environment:
      vars:
        ANDROID_BUILD_TYPE: debug  # Change to 'release' if needed
        ANDROID_HOME: $HOME/android-sdk
        ANDROID_SDK_ROOT: $ANDROID_HOME
      java: 17
    scripts:
      - name: Install Android SDK & Dependencies
        script: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip
          
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.1.8937393"
      - name: Build APK
        script: |
          cd android
          ./gradlew assemble${ANDROID_BUILD_TYPE^}
    artifacts:
      - android/app/build/outputs/apk/${ANDROID_BUILD_TYPE}/app-${ANDROID_BUILD_TYPE}.apk
    publishing:
      email:
        recipients:
          - "hossammohammed2040@gmail.com"  # Change this to receive the APK
